export type Article = {
    id: number;
    title: string;
    slug: string;
    content: string | null | string;
    excerpt: string;
    author_id: number;
    authors?: { id: number; name: string }[];
    category_id: number;
    published: boolean;
    published_date: string | null;
    featured_image: string | null;
    meta_title: string | null;
    meta_description: string | null;
    meta_keywords: string[] | null | string;
    is_featured: boolean;
    view_count: number;
    tags: string[] | string;
    created_date: string;
    updated_date: string;
};
